# Generated by Django 5.0 on 2024-01-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_of_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
