# Generated by Django 5.0 on 2024-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_of_study', '0002_fieldofstudy_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='date_deleting',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
