# Generated by Django 5.0 on 2024-01-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
