# Generated by Django 5.0 on 2024-01-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='date_deleting',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
