# Generated by Django 5.0 on 2024-01-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_professors_date_deleting_professors_is_deleted'),
        ('specialisations', '0003_remove_specialisations_professors'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='specialisations',
            field=models.ManyToManyField(to='specialisations.specialisations'),
        ),
    ]
