# Generated by Django 5.0 on 2024-01-04 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_of_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_of_study.fieldofstudy')),
            ],
        ),
    ]
