# Generated by Django 5.0 on 2024-01-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisations',
            name='date_deleting',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='specialisations',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
