# Generated by Django 5.0 on 2024-01-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('specialisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialisations',
            name='specialiser',
            field=models.ManyToManyField(to='professors.professors'),
        ),
    ]
