# Generated by Django 5.0 on 2024-01-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisations', '0002_specialisations_date_deleting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialisations',
            name='professors',
        ),
    ]
