# Generated by Django 5.0 on 2024-01-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisations', '0002_specialisations_specialiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialisations',
            old_name='specialiser',
            new_name='professors',
        ),
    ]
