# Generated by Django 5.0 on 2024-01-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='serialNumber',
            field=models.CharField(default=None, max_length=9),
        ),
    ]
