# Generated by Django 5.0 on 2024-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_year', '0002_schoolyear_is_deleted'),
        ('student', '0002_student_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_year',
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.ManyToManyField(to='school_year.schoolyear'),
        ),
    ]
