# Generated by Django 5.0 on 2024-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_is_deleted_remove_student_school_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_deleting',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
