<<<<<<< HEAD
# Generated by Django 5.0 on 2024-01-05 21:56
=======
# Generated by Django 5.0 on 2024-01-05 21:24
>>>>>>> 2091af7fb5410523961ec2c1922506a6d911165f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
