# Generated by Django 5.0 on 2024-01-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
