# Generated by Django 5.0 on 2024-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rooms_date_deleting'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='nbrePlace',
            field=models.IntegerField(default=0),
        ),
    ]
