<<<<<<< HEAD
# Generated by Django 5.0 on 2024-01-05 21:56
=======
# Generated by Django 5.0 on 2024-01-05 21:24
>>>>>>> 2091af7fb5410523961ec2c1922506a6d911165f

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('rooms', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(default=None)),
                ('result', models.IntegerField(default=None)),
<<<<<<< HEAD
                ('professors', models.ManyToManyField(to='professors.professors')),
=======
>>>>>>> 2091af7fb5410523961ec2c1922506a6d911165f
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='DefenseProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=None)),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defense.defense')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professors')),
            ],
        ),
        migrations.AddField(
            model_name='defense',
            name='professors',
            field=models.ManyToManyField(through='defense.DefenseProfessor', to='professors.professors'),
        ),
>>>>>>> 2091af7fb5410523961ec2c1922506a6d911165f
    ]
