# Generated by Django 5.0 on 2024-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='professors',
            field=models.ManyToManyField(to='professors.professors'),
        ),
    ]
