# Generated by Django 5.0 on 2024-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0002_alter_defenseprofessor_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='date_deleting',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='defense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
