# Generated by Django 5.0 on 2024-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0004_alter_defense_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='duration',
            field=models.IntegerField(default=2),
        ),
    ]
