# Generated by Django 5.0 on 2024-01-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0005_defense_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='date_time',
        ),
        migrations.AddField(
            model_name='defense',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='defense',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
