# Generated by Django 5.0 on 2024-01-22 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0006_remove_defense_date_time_defense_date_defense_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenseprofessor',
            name='mark',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
