# Generated by Django 5.0 on 2024-01-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defense', '0007_alter_defenseprofessor_mark'),
        ('professors', '0003_professors_fieldofstudy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defenseprofessor',
            unique_together={('defense', 'professor')},
        ),
    ]
